const fs = require('fs');
const lines = fs.readFileSync('js/features/echoes.js', 'utf8').split('\n');

const newWiring = [
'  backdrop.querySelector(\'#echoLyricInput\').oninput = e => {',
'    const n = e.target.value.length;',
'    backdrop.querySelector(\'#echoCharCount\').textContent = n;',
'    backdrop.querySelector(\'#echoSubmitBtn\').disabled = n < 2;',
'  };',
'  backdrop.querySelectorAll(\'.echo-vibe-opt\').forEach(btn => {',
'    btn.onclick = () => {',
'      backdrop.querySelectorAll(\'.echo-vibe-opt\').forEach(b => b.classList.remove(\'active\'));',
'      btn.classList.add(\'active\');',
'    };',
'  });',
'  // ── Smart search wiring ──',
'  let echoSearchDebounce;',
'  let echoLastQuery = \'\';',
'  const echoSmartInput = backdrop.querySelector(\'#echoSmartInput\');',
'  const echoSearchSheet = backdrop.querySelector(\'#echoSearchSheet\');',
'  const echoSearchStatus = backdrop.querySelector(\'#echoSearchStatus\');',
'  const echoSearchResults = backdrop.querySelector(\'#echoSearchResults\');',
'  const echoSearchSpinner = backdrop.querySelector(\'#echoSearchSpinner\');',
'  const echoClearSearch = backdrop.querySelector(\'#echoClearSearch\');',
'',
'  function echoOpenSheet() { echoSearchSheet.classList.remove(\'hidden\'); setTimeout(() => echoSearchSheet.classList.add(\'open\'), 10); }',
'  function echoCloseSheet() { echoSearchSheet.classList.remove(\'open\'); setTimeout(() => echoSearchSheet.classList.add(\'hidden\'), 220); }',
'',
'  echoSmartInput.addEventListener(\'input\', () => {',
'    const val = echoSmartInput.value.trim();',
'    echoClearSearch.style.display = val ? \'\' : \'none\';',
'    clearTimeout(echoSearchDebounce);',
'    if (!val) { echoCloseSheet(); echoLastQuery = \'\'; return; }',
'    if (val.length < 2) return;',
'    echoSearchSpinner.style.display = \'\';',
'    echoSearchStatus.innerHTML = \'\';',
'    echoOpenSheet();',
'    echoSearchDebounce = setTimeout(() => echoRunSearch(val), 380);',
'  });',
'',
'  echoClearSearch.onclick = () => {',
'    echoSmartInput.value = \'\';',
'    echoClearSearch.style.display = \'none\';',
'    echoCloseSheet();',
'    echoLastQuery = \'\';',
'    echoSmartInput.focus();',
'  };',
'',
'  backdrop.querySelector(\'#echoChangeSong\').onclick = () => {',
'    document.getElementById(\'echoSongInput\').value = \'\';',
'    document.getElementById(\'echoArtistInput\').value = \'\';',
'    document.getElementById(\'echoSongPill\').classList.add(\'hidden\');',
'    document.getElementById(\'echoLyricWrap\').style.display = \'none\';',
'    document.getElementById(\'echoLyricInput\').value = \'\';',
'    document.getElementById(\'echoCharCount\').textContent = \'0\';',
'    document.getElementById(\'echoSubmitBtn\').disabled = true;',
'    document.getElementById(\'echoSmartSearchWrap\').style.display = \'\';',
'    echoSmartInput.value = \'\';',
'    echoClearSearch.style.display = \'none\';',
'    echoLastQuery = \'\';',
'    echoSmartInput.focus();',
'  };',
'',
'  async function echoRunSearch(query) {',
'    if (query === echoLastQuery) return;',
'    echoLastQuery = query;',
'    echoSearchSpinner.style.display = \'\';',
'    echoSearchResults.innerHTML = \'\';',
'    try {',
'      const res = await fetch(\'/api/genius?lyric=\' + encodeURIComponent(query));',
'      const data = await res.json();',
'      echoSearchSpinner.style.display = \'none\';',
'      if (!res.ok || !data.results || !data.results.length) {',
'        echoSearchStatus.innerHTML = \'<span style="font-family:Space Mono,monospace;font-size:0.5rem;color:rgba(255,255,255,0.28);text-transform:uppercase;letter-spacing:2px">No results found</span>\';',
'        return;',
'      }',
'      echoSearchStatus.innerHTML = \'<span style="font-family:Space Mono,monospace;font-size:0.5rem;color:rgba(255,255,255,0.28);text-transform:uppercase;letter-spacing:2px">Select the right song</span>\';',
'      data.results.forEach(r => {',
'        const card = document.createElement(\'div\');',
'        card.className = \'search-result-item\';',
'        card.style.cssText = \'display:flex;align-items:center;gap:10px;padding:10px 14px;cursor:pointer;transition:background 0.15s;border-bottom:1px solid rgba(255,255,255,0.04)\';',
'        const artHtml = r.artwork',
'          ? \'<img src="\' + r.artwork + \'" style="width:40px;height:40px;border-radius:8px;object-fit:cover;flex-shrink:0" alt=""/>\'',
'          : \'<div style="width:40px;height:40px;border-radius:8px;background:rgba(255,255,255,0.05);flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:1rem;opacity:0.4">\u266a</div>\';',
'        const srcLabel = r.source === \'itunes\' ? \'iTunes\' : \'Genius\';',
'        card.innerHTML = artHtml',
'          + \'<div style="flex:1;min-width:0">\'',
'          + \'<div style="font-size:0.82rem;font-weight:700;color:#fff;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">\' + r.song + \'</div>\'',
'          + \'<div style="font-size:0.65rem;color:rgba(255,255,255,0.4);overflow:hidden;text-overflow:ellipsis;white-space:nowrap">\' + r.artist + \'</div>\'',
'          + \'</div>\'',
'          + \'<span style="font-family:Space Mono,monospace;font-size:0.46rem;font-weight:700;padding:3px 8px;border-radius:6px;background:rgba(232,197,71,0.08);color:rgba(232,197,71,0.7);border:1px solid rgba(232,197,71,0.2);flex-shrink:0">\' + srcLabel + \'</span>\';',
'        card.onmouseenter = () => { card.style.background = \'rgba(232,197,71,0.06)\'; };',
'        card.onmouseleave = () => { card.style.background = \'\'; };',
'        card.onclick = () => {',
'          document.getElementById(\'echoSongInput\').value = r.song;',
'          document.getElementById(\'echoArtistInput\').value = r.artist;',
'          const pill = document.getElementById(\'echoSongPill\');',
'          const pillName = document.getElementById(\'echoSongPillName\');',
'          const pillArtist = document.getElementById(\'echoSongPillArtist\');',
'          const pillArt = document.getElementById(\'echoSongPillArt\');',
'          if (pillName) pillName.textContent = r.song;',
'          if (pillArtist) pillArtist.textContent = r.artist;',
'          if (pillArt && r.artwork) pillArt.src = r.artwork;',
'          if (pill) pill.classList.remove(\'hidden\');',
'          document.getElementById(\'echoSmartSearchWrap\').style.display = \'none\';',
'          const lyricWrap = document.getElementById(\'echoLyricWrap\');',
'          const lyricInput = document.getElementById(\'echoLyricInput\');',
'          if (lyricWrap) lyricWrap.style.display = \'block\';',
'          if (lyricInput) {',
'            lyricInput.placeholder = r.source === \'itunes\'',
'              ? \'Type the lyric from \' + r.song + \' you want to share\u2026\'',
'              : \'The lyric that answers this one\u2026\';',
'            setTimeout(() => lyricInput.focus(), 80);',
'          }',
'          echoCloseSheet();',
'          echoLastQuery = \'\';',
'        };',
'        echoSearchResults.appendChild(card);',
'      });',
'    } catch(e) {',
'      echoSearchSpinner.style.display = \'none\';',
'    }',
'  }',
'}',
];

// Replace lines 401-447 (0-indexed 400-446)
lines.splice(400, 47, ...newWiring);

fs.writeFileSync('js/features/echoes.js', lines.join('\n'), 'utf8');
console.log('Done');
