const fs = require('fs');
const lines = fs.readFileSync('js/features/echoes.js', 'utf8').split('\n');

// Find the line numbers (0-indexed)
const startLine = lines.findIndex(l => l.includes('let _echoLastQuery'));
const endLine   = lines.findIndex(l => l.includes('async function fillEchoSongMeta'));

const newFunctions = [
  "let _echoLastQuery = '';",
  "",
  "async function runEchoSmartSearch(query) {",
  "  if (query === _echoLastQuery) return;",
  "  _echoLastQuery = query;",
  "  const spinner   = document.getElementById('echoSearchSpinner');",
  "  const resultsEl = document.getElementById('echoSearchResults');",
  "  if (spinner)   spinner.style.display = '';",
  "  if (resultsEl) { resultsEl.style.display = 'none'; resultsEl.innerHTML = ''; }",
  "  try {",
  "    const res  = await fetch('/api/genius?lyric=' + encodeURIComponent(query));",
  "    const data = await res.json();",
  "    if (spinner) spinner.style.display = 'none';",
  "    if (!res.ok || !data.results || !data.results.length) {",
  "      if (resultsEl) {",
  "        resultsEl.innerHTML = '<div style=\"padding:10px 12px;font-family:Space Mono,monospace;font-size:0.5rem;color:rgba(255,255,255,0.28);text-transform:uppercase;letter-spacing:2px\">No results found</div>';",
  "        resultsEl.style.display = 'block';",
  "      }",
  "      return;",
  "    }",
  "    renderEchoSmartResults(data.results);",
  "  } catch (e) {",
  "    if (spinner) spinner.style.display = 'none';",
  "  }",
  "}",
  "",
  "function selectEchoResult(r) {",
  "  const songInput   = document.getElementById('echoSongInput');",
  "  const artistInput = document.getElementById('echoArtistInput');",
  "  if (songInput)   songInput.value   = r.song;",
  "  if (artistInput) artistInput.value = r.artist;",
  "  const pillName   = document.getElementById('echoSongPillName');",
  "  const pillArtist = document.getElementById('echoSongPillArtist');",
  "  const pillArt    = document.getElementById('echoSongPillArt');",
  "  const pill       = document.getElementById('echoSongPill');",
  "  if (pillName)   pillName.textContent   = r.song;",
  "  if (pillArtist) pillArtist.textContent = r.artist;",
  "  if (pillArt && r.artwork) { pillArt.src = r.artwork; pillArt.style.display = ''; }",
  "  if (pill) pill.style.display = 'flex';",
  "  const sw = document.getElementById('echoSmartSearchWrap');",
  "  if (sw) sw.style.display = 'none';",
  "  const lyricWrap  = document.getElementById('echoLyricWrap');",
  "  const lyricInput = document.getElementById('echoLyricInput');",
  "  if (lyricWrap) lyricWrap.style.display = 'block';",
  "  if (lyricInput) {",
  "    lyricInput.placeholder = r.source === 'itunes'",
  "      ? 'Type the lyric from ' + r.song + ' you want to share\u2026'",
  "      : 'The lyric that answers this one\u2026';",
  "    setTimeout(() => lyricInput.focus(), 80);",
  "  }",
  "  const resultsEl = document.getElementById('echoSearchResults');",
  "  if (resultsEl) { resultsEl.style.display = 'none'; resultsEl.innerHTML = ''; }",
  "  _echoLastQuery = '';",
  "}",
  "",
  "function renderEchoSmartResults(results) {",
  "  const el = document.getElementById('echoSearchResults');",
  "  if (!el) return;",
  "  el.innerHTML = '';",
  "  el.style.display = 'block';",
  "  const label = document.createElement('div');",
  "  label.style.cssText = 'padding:8px 12px 4px;font-family:Space Mono,monospace;font-size:0.48rem;font-weight:700;color:rgba(255,255,255,0.28);text-transform:uppercase;letter-spacing:2px';",
  "  label.textContent = 'Select the right song';",
  "  el.appendChild(label);",
  "  results.forEach(r => {",
  "    const card = document.createElement('div');",
  "    card.style.cssText = 'display:flex;align-items:center;gap:10px;padding:9px 12px;cursor:pointer;transition:background 0.15s;border-bottom:1px solid rgba(255,255,255,0.04)';",
  "    const artHtml = r.artwork",
  "      ? '<img src=\"' + r.artwork + '\" style=\"width:36px;height:36px;border-radius:7px;object-fit:cover;flex-shrink:0\" alt=\"\"/>'",
  "      : '<div style=\"width:36px;height:36px;border-radius:7px;background:rgba(255,255,255,0.05);flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:1rem;opacity:0.4\">\u266a</div>';",
  "    const srcLabel = r.source === 'itunes' ? 'iTunes' : 'Genius';",
  "    card.innerHTML = artHtml",
  "      + '<div style=\"flex:1;min-width:0\">'",
  "      + '<div style=\"font-size:0.78rem;font-weight:700;color:#fff;overflow:hidden;text-overflow:ellipsis;white-space:nowrap\">' + r.song + '</div>'",
  "      + '<div style=\"font-size:0.62rem;color:rgba(255,255,255,0.4);overflow:hidden;text-overflow:ellipsis;white-space:nowrap\">' + r.artist + '</div>'",
  "      + '</div>'",
  "      + '<span style=\"font-family:Space Mono,monospace;font-size:0.46rem;font-weight:700;padding:3px 8px;border-radius:6px;background:rgba(232,197,71,0.08);color:rgba(232,197,71,0.7);border:1px solid rgba(232,197,71,0.2);flex-shrink:0\">' + srcLabel + '</span>';",
  "    card.onmouseenter = () => { card.style.background = 'rgba(232,197,71,0.06)'; };",
  "    card.onmouseleave = () => { card.style.background = ''; };",
  "    card.onclick = () => selectEchoResult(r);",
  "    el.appendChild(card);",
  "  });",
  "}",
  "",
];

console.log('Replacing lines', startLine, 'to', endLine - 1);
const result = [...lines.slice(0, startLine), ...newFunctions, ...lines.slice(endLine)];
fs.writeFileSync('js/features/echoes.js', result.join('\n'), 'utf8');
console.log('Done');
