const fs = require('fs');
const path = require('path');
const out = path.join(__dirname, 'js/ui/composer/integrations.js');
const parts = [];
parts.push('/* MARGO integrations.js v7.0 */');
parts.push('');
parts.push('let youtubeData=null,geniusResult=null,geniusTimer=null,lastQuery="",searchCache={},isSheetOpen=false;');
parts.push('');
parts.push('const PLACEHOLDERS=["Type a lyric\u2026","Or a song title\u2026","Or an artist name\u2026","Any words you remember\u2026"];');
parts.push('');
parts.push('function startAnimatedPlaceholder(){');
parts.push('  const input=document.getElementById("smartSearchInput");');
parts.push('  if(!input)return;');
parts.push('  let i=0,charIndex=0,isDeleting=false,current=PLACEHOLDERS[0];');
parts.push('  const speed={type:55,del:28,pause:1800};');
parts.push('  function tick(){');
parts.push('    if(document.activeElement===input||input.value)return;');
parts.push('    if(!isDeleting&&charIndex<=current.length){input.placeholder=current.slice(0,charIndex++);setTimeout(tick,speed.type);}');
parts.push('    else if(!isDeleting&&charIndex>current.length){isDeleting=true;setTimeout(tick,speed.pause);}');
parts.push('    else if(isDeleting&&charIndex>0){input.placeholder=current.slice(0,charIndex--);setTimeout(tick,speed.del);}');
parts.push('    else{isDeleting=false;i=(i+1)%PLACEHOLDERS.length;current=PLACEHOLDERS[i];charIndex=0;setTimeout(tick,300);}');
parts.push('  }');
parts.push('  tick();');
parts.push('}');
parts.push('');
parts.push('function initGeniusIdentify(){');
parts.push('  injectSearchSheet();');
parts.push('  startAnimatedPlaceholder();');
parts.push('  const input=document.getElementById("smartSearchInput");');
parts.push('  if(!input)return;');
parts.push('  input.addEventListener("input",onSmartInput);');
parts.push('  input.addEventListener("focus",function(){if(input.value.trim().length>=2)openSheet();});');
parts.push('  document.addEventListener("pointerdown",function(e){');
parts.push('    const sheet=document.getElementById("searchSheet");');
parts.push('    const wrap=document.getElementById("smartSearchWrap");');
parts.push('    if(sheet&&!sheet.contains(e.target)&&wrap&&!wrap.contains(e.target))closeSheet();');
parts.push('  });');
parts.push('}');
parts.push('');
parts.push('function onSmartInput(){');
parts.push('  const input=document.getElementById("smartSearchInput");');
parts.push('  const val=input.value.trim();');
parts.push('  clearTimeout(geniusTimer);');
parts.push('  if(!val){clearSongSelection();closeSheet();return;}');
parts.push('  if(geniusResult){geniusResult=null;clearSongPill();clearYoutubePreview();}');
parts.push('  if(val.length<2)return;');
parts.push('  showSearchingState();');
parts.push('  openSheet();');
parts.push('  const cacheKey=val.toLowerCase();');
parts.push('  if(searchCache[cacheKey]){renderSheetResults(searchCache[cacheKey]);return;}');
parts.push('  geniusTimer=setTimeout(function(){runSmartSearch(val);},380);');
parts.push('}');
parts.push('');
parts.push('async function runSmartSearch(query){');
parts.push('  if(query===lastQuery)return;');
parts.push('  lastQuery=query;');
parts.push('  try{');
parts.push('    const res=await fetch("/api/genius?lyric="+encodeURIComponent(query));');
parts.push('    const data=await res.json();');
parts.push('    const results=(res.ok&&data.results&&data.results.length)?data.results:[];');
parts.push('    searchCache[query.toLowerCase()]=results;');
parts.push('    if(results.length)renderSheetResults(results);');
parts.push('    else showNoResults();');
parts.push('  }catch(err){showNoResults();}');
parts.push('}');
parts.push('');
parts.push('function injectSearchSheet(){');
parts.push('  if(document.getElementById("searchSheet"))return;');
parts.push('  const shareInputs=document.getElementById("shareInputs");');
parts.push('  if(!shareInputs)return;');
parts.push('  const q=\'"\';');
parts.push('  shareInputs.innerHTML=');
parts.push('    "<div id="+q+"smartSearchWrap"+q+" class="+q+"smart-search-wrap"+q+">"');
parts.push('    +"<div class="+q+"smart-search-field"+q+">"');
parts.push('    +"<span class="+q+"smart-search-icon"+q+"><svg width="+q+"14"+q+" height="+q+"14"+q+" viewBox="+q+"0 0 24 24"+q+" fill="+q+"none"+q+" stroke="+q+"currentColor"+q+" stroke-width="+q+"2.5"+q+" stroke-linecap="+q+"round"+q+" stroke-linejoin="+q+"round"+q+"><circle cx="+q+"11"+q+" cy="+q+"11"+q+" r="+q+"8"+q+"/><path d="+q+"m21 21-4.35-4.35"+q+"/></svg></span>"');
parts.push('    +"<input id="+q+"smartSearchInput"+q+" type="+q+"text"+q+" inputmode="+q+"text"+q+" autocomplete="+q+"off"+q+" autocorrect="+q+"off"+q+" spellcheck="+q+"false"+q+" class="+q+"smart-search-input"+q+" placeholder="+q+"Type a lyric\u2026"+q+"/>"');
parts.push('    +"<span id="+q+"searchSpinner"+q+" class="+q+"search-spinner hidden"+q+"></span>"');
parts.push('    +"<button id="+q+"clearSearchBtn"+q+" class="+q+"clear-search-btn hidden"+q+" aria-label="+q+"Clear"+q+">\u00d7</button>"');
parts.push('    +"</div>"');
parts.push('    +"<div id="+q+"songPill"+q+" class="+q+"song-pill hidden"+q+">"');
parts.push('    +"<span class="+q+"song-pill-art-wrap"+q+"><img id="+q+"songPillArt"+q+" class="+q+"song-pill-art"+q+" src="+q+q+" alt="+q+q+"/><span class="+q+"song-pill-art-fallback"+q+">\u266a</span></span>"');
parts.push('    +"<span class="+q+"song-pill-info"+q+"><span id="+q+"songPillName"+q+" class="+q+"song-pill-name"+q+"></span><span id="+q+"songPillArtist"+q+" class="+q+"song-pill-artist"+q+"></span></span>"');
parts.push('    +"<button id="+q+"changeSongBtn"+q+" class="+q+"song-pill-change"+q+">Change</button>"');
parts.push('    +"</div></div>"');
parts.push('    +"<div id="+q+"searchSheet"+q+" class="+q+"search-sheet hidden"+q+">"');
parts.push('    +"<div class="+q+"search-sheet-inner"+q+">"');
parts.push('    +"<div id="+q+"searchSheetStatus"+q+" class="+q+"search-sheet-status"+q+"></div>"');
parts.push('    +"<div id="+q+"searchSheetResults"+q+" class="+q+"search-sheet-results"+q+"></div>"');
parts.push('    +"</div></div>"');
parts.push('    +"<input id="+q+"songInput"+q+" type="+q+"hidden"+q+" value="+q+q+"/>"');
parts.push('    +"<input id="+q+"artistInput"+q+" type="+q+"hidden"+q+" value="+q+q+"/>";');
parts.push('  document.getElementById("clearSearchBtn").addEventListener("click",function(){');
parts.push('    clearSongSelection();');
parts.push('    var input=document.getElementById("smartSearchInput");');
parts.push('    if(input){input.value="";input.focus();}');
parts.push('    closeSheet();');
parts.push('  });');
parts.push('  document.getElementById("changeSongBtn").addEventListener("click",function(){');
parts.push('    geniusResult=null;clearSongPill();clearYoutubePreview();');
parts.push('    var input=document.getElementById("smartSearchInput");');
parts.push('    if(input){input.value="";input.focus();}');
parts.push('    hideSongPill();');
parts.push('  });');
parts.push('}');
parts.push('');
parts.push('function openSheet(){');
parts.push('  const sheet=document.getElementById("searchSheet");');
parts.push('  if(!sheet||isSheetOpen)return;');
parts.push('  sheet.classList.remove("hidden");');
parts.push('  requestAnimationFrame(function(){sheet.classList.add("open");});');
parts.push('  isSheetOpen=true;');
parts.push('}');
parts.push('');
parts.push('function closeSheet(){');
parts.push('  const sheet=document.getElementById("searchSheet");');
parts.push('  if(!sheet)return;');
parts.push('  sheet.classList.remove("open");');
parts.push('  setTimeout(function(){sheet.classList.add("hidden");},220);');
parts.push('  isSheetOpen=false;');
parts.push('}');
parts.push('');
parts.push('function showSearchingState(){');
parts.push('  const status=document.getElementById("searchSheetStatus");');
parts.push('  const results=document.getElementById("searchSheetResults");');
parts.push('  const spinner=document.getElementById("searchSpinner");');
parts.push('  const q=\'"\';');
parts.push('  if(status)status.innerHTML="<span class="+q+"search-identifying"+q+"><span class="+q+"search-pulse"+q+"></span>Identifying\u2026</span>";');
parts.push('  if(results)results.innerHTML="";');
parts.push('  if(spinner)spinner.classList.remove("hidden");');
parts.push('}');
parts.push('');
parts.push('function showNoResults(){');
parts.push('  const status=document.getElementById("searchSheetStatus");');
parts.push('  const results=document.getElementById("searchSheetResults");');
parts.push('  const spinner=document.getElementById("searchSpinner");');
parts.push('  const q=\'"\';');
parts.push('  if(status)status.innerHTML="<span class="+q+"search-no-result"+q+">Try a different line or song name</span>";');
parts.push('  if(results)results.innerHTML="";');
parts.push('  if(spinner)spinner.classList.add("hidden");');
parts.push('}');
parts.push('');
parts.push('function renderSheetResults(results){');
parts.push('  const status=document.getElementById("searchSheetStatus");');
parts.push('  const list=document.getElementById("searchSheetResults");');
parts.push('  const spinner=document.getElementById("searchSpinner");');
parts.push('  const q=\'"\';');
parts.push('  if(spinner)spinner.classList.add("hidden");');
parts.push('  if(status)status.innerHTML="<span class="+q+"search-found-label"+q+">Select the right song</span>";');
parts.push('  if(!list)return;');
parts.push('  list.innerHTML="";');
parts.push('  results.forEach(function(r,idx){');
parts.push('    const song=decodeHTML(r.song||""),artist=decodeHTML(r.artist||"");');
parts.push('    const card=document.createElement("div");');
parts.push('    card.className="search-result-card";');
parts.push('    card.style.animationDelay=idx*55+"ms";');
parts.push('    const img=r.artwork');
parts.push('      ? "<img src="+q+r.artwork+q+" class="+q+"search-result-art"+q+" alt="+q+q+"/>"');
parts.push('      : "<div class="+q+"search-result-art search-result-art-fallback"+q+">\u266a</div>";');
parts.push('    card.innerHTML=img');
parts.push('      +"<div class="+q+"search-result-info"+q+"><div class="+q+"search-result-song"+q+">"+song+"</div><div class="+q+"search-result-artist"+q+">"+artist+"</div></div>"');
parts.push('      +"<span class="+q+"search-result-use"+q+">Use</span>";');
parts.push('    card.addEventListener("pointerdown",function(e){');
parts.push('      e.preventDefault();');
parts.push('      selectResult(Object.assign({},r,{song:song,artist:artist}),card);');
parts.push('    });');
parts.push('    list.appendChild(card);');
parts.push('  });');
parts.push('}');
parts.push('');
parts.push('function selectResult(result,card){');
parts.push('  document.querySelectorAll(".search-result-card").forEach(function(c){c.classList.remove("selected");});');
parts.push('  if(card){');
parts.push('    card.classList.add("selected");');
parts.push('    const tag=card.querySelector(".search-result-use");');
parts.push('    if(tag)tag.textContent="\u2713";');
parts.push('  }');
parts.push('  geniusResult=result;');
parts.push('  const songEl=document.getElementById("songInput");');
parts.push('  const artistEl=document.getElementById("artistInput");');
parts.push('  if(songEl)songEl.value=result.song;');
parts.push('  if(artistEl)artistEl.value=result.artist;');
parts.push('  showSongPill(result);');
parts.push('  if(result.id)fetchGeniusDetail(result.id);');
parts.push('  clearYoutubePreview();');
parts.push('  fetchYoutubeData(result.song,result.artist);');
parts.push('  setTimeout(function(){closeSheet();},280);');
parts.push('}');
parts.push('');
parts.push('function showSongPill(result){');
parts.push('  const pill=document.getElementById("songPill");');
parts.push('  const nameEl=document.getElementById("songPillName");');
parts.push('  const artEl=document.getElementById("songPillArtist");');
parts.push('  const imgEl=document.getElementById("songPillArt");');
parts.push('  const input=document.getElementById("smartSearchInput");');
parts.push('  if(nameEl)nameEl.textContent=result.song;');
parts.push('  if(artEl)artEl.textContent=result.artist;');
parts.push('  if(imgEl&&result.artwork){imgEl.src=result.artwork;imgEl.style.display="block";}');
parts.push('  if(pill)pill.classList.remove("hidden");');
parts.push('  const field=input&&input.closest(".smart-search-field");');
parts.push('  if(field)field.style.display="none";');
parts.push('  const wrap=document.getElementById("smartSearchWrap");');
parts.push('  if(wrap)wrap.classList.add("has-selection");');
parts.push('}');
parts.push('');
parts.push('function hideSongPill(){');
parts.push('  const pill=document.getElementById("songPill");');
parts.push('  const input=document.getElementById("smartSearchInput");');
parts.push('  const wrap=document.getElementById("smartSearchWrap");');
parts.push('  if(pill)pill.classList.add("hidden");');
parts.push('  const field=input&&input.closest(".smart-search-field");');
parts.push('  if(field)field.style.display="";');
parts.push('  if(wrap)wrap.classList.remove("has-selection");');
parts.push('}');
parts.push('');
parts.push('function clearSongPill(){');
parts.push('  hideSongPill();');
parts.push('  const s=document.getElementById("songInput"),a=document.getElementById("artistInput");');
parts.push('  if(s)s.value="";if(a)a.value="";');
parts.push('}');
parts.push('');
parts.push('function clearSongSelection(){');
parts.push('  geniusResult=null;lastQuery="";');
parts.push('  clearSongPill();clearYoutubePreview();');
parts.push('  const sp=document.getElementById("searchSpinner");');
parts.push('  if(sp)sp.classList.add("hidden");');
parts.push('}');
parts.push('');
parts.push('function initYoutubeAutofetch(){}');
parts.push('');
parts.push('async function fetchYoutubeData(song,artist){');
parts.push('  const cleanSong=song.replace(/\\s*[\\(\\[].*?[\\)\\]]/g,"").trim();');
parts.push('  const cleanArtist=artist.replace(/\\s*feat\\..*$/i,"").replace(/\\s*ft\\..*$/i,"").trim();');
parts.push('  showYtLoading();youtubeData=null;');
parts.push('  try{');
parts.push('    const res=await fetch("/api/youtube?song="+encodeURIComponent(cleanSong)+"&artist="+encodeURIComponent(cleanArtist));');
parts.push('    const data=await res.json();');
parts.push('    if(!res.ok||data.error||(!data.videoId&&!data.thumbnail)){clearYoutubePreview();return;}');
parts.push('    youtubeData=data;renderYtCard(data);');
parts.push('  }catch(_){clearYoutubePreview();}');
parts.push('}');
parts.push('');
parts.push('function showYtLoading(){');
parts.push('  clearYoutubePreview();');
parts.push('  const q=\'"\';');
parts.push('  const card=document.createElement("div");');
parts.push('  card.id="youtubePreview";card.className="yt-card";');
parts.push('  card.innerHTML="<div class="+q+"yt-loading"+q+"><span class="+q+"m-spinner"+q+"></span>Looking up on YouTube, Deezer, Apple Music\u2026</div>";');
parts.push('  insertAfterSearch(card);');
parts.push('}');
parts.push('');
parts.push('function renderYtCard(data){');
parts.push('  clearYoutubePreview();');
parts.push('  const source=data.source||"youtube";');
parts.push('  const links=[];');
parts.push('  const q=\'"\';');
parts.push('  if(data.youtubeUrl)links.push("<a href="+q+data.youtubeUrl+q+" target="+q+"_blank"+q+" rel="+q+"noopener"+q+" class="+q+"yt-listen-link yt-link-yt"+q+">YouTube</a>");');
parts.push('  if(data.deezerUrl)links.push("<a href="+q+data.deezerUrl+q+" target="+q+"_blank"+q+" rel="+q+"noopener"+q+" class="+q+"yt-listen-link yt-link-dz"+q+">Deezer</a>");');
parts.push('  if(data.itunesUrl)links.push("<a href="+q+data.itunesUrl+q+" target="+q+"_blank"+q+" rel="+q+"noopener"+q+" class="+q+"yt-listen-link yt-link-it"+q+">Apple Music</a>");');
parts.push('  const cls=source==="youtube"?"yt-found-yt":source==="deezer"?"yt-found-dz":"yt-found-it";');
parts.push('  const thumb=data.thumbnail||data.thumbnailSm;');
parts.push('  const card=document.createElement("div");');
parts.push('  card.id="youtubePreview";card.className="yt-card";');
parts.push('  card.innerHTML="<div class="+q+"yt-card-inner"+q+">"');
parts.push('    +(thumb?"<div class="+q+"yt-thumb-wrap"+q+"><img src="+q+thumb+q+" class="+q+"yt-thumb"+q+" alt="+q+decodeHTML(data.title||"")+q+"/></div>":"")');
parts.push('    +"<div class="+q+"yt-info"+q+"><div class="+q+"yt-title"+q+">"+decodeHTML(data.title||"")+"</div>"');
parts.push('    +"<div class="+q+"yt-channel"+q+">"+decodeHTML(data.channel||data.collectionName||"")+"</div>"');
parts.push('    +(links.length?"<div class="+q+"yt-links-row"+q+">"+links.join("")+"</div>":"")');
parts.push('    +"</div><span class="+q+"yt-found-tag "+cls+q+">Found</span></div>";');
parts.push('  insertAfterSearch(card);');
parts.push('  const ytLink=document.getElementById("youtubeLink");');
parts.push('  if(ytLink&&!ytLink.value&&data.videoId&&data.youtubeUrl)ytLink.value=data.youtubeUrl;');
parts.push('}');
parts.push('');
parts.push('function insertAfterSearch(el){');
parts.push('  const wrap=document.getElementById("smartSearchWrap");');
parts.push('  if(wrap)wrap.parentNode.insertBefore(el,wrap.nextSibling);');
parts.push('}');
parts.push('');
parts.push('function clearYoutubePreview(){');
parts.push('  youtubeData=null;');
parts.push('  const el=document.getElementById("youtubePreview");');
parts.push('  if(el)el.remove();');
parts.push('}');
parts.push('');
parts.push('async function fetchGeniusDetail(id){');
parts.push('  try{');
parts.push('    const res=await fetch("/api/genius?id="+id);');
parts.push('    const data=await res.json();');
parts.push('    if(!res.ok||data.error)return;');
parts.push('    geniusResult=Object.assign({},geniusResult,{');
parts.push('      album:data.album||null,');
parts.push('      releaseDate:data.releaseDate||null,');
parts.push('      featuredArtists:data.featuredArtists||[],');
parts.push('      writers:data.writers||[],');
parts.push('      producers:data.producers||[]');
parts.push('    });');
parts.push('  }catch(_){}');
parts.push('}');
parts.push('');
parts.push('function closeAutocomplete(){closeSheet();}');
fs.writeFileSync(out, parts.join('\n'), 'utf8');
console.log('done, lines:', parts.length);
