const fs = require('fs');
const path = require('path');
const out = path.join(__dirname, 'js/ui/composer/integrations.js');
const parts = [];

parts.push('/* MARGO integrations.js v7.1 */');
parts.push('');
parts.push('let youtubeData=null,geniusResult=null,geniusTimer=null,lastQuery="",searchCache={},isSheetOpen=false;');
parts.push('');
parts.push('function initGeniusIdentify(){');
parts.push('  injectSearchSheet();');
parts.push('  const input=document.getElementById("smartSearchInput");');
parts.push('  if(!input)return;');
parts.push('  input.addEventListener("input",onSmartInput);');
parts.push('  input.addEventListener("focus",function(){if(input.value.trim().length>=2)openSheet();});');
parts.push('  document.addEventListener("pointerdown",function(e){');
parts.push('    const sheet=document.getElementById("searchSheet");');
parts.push('    const wrap=document.getElementById("smartSearchWrap");');
parts.push('    if(sheet&&!sheet.contains(e.target)&&wrap&&!wrap.contains(e.target))closeSheet();');
parts.push('  });');
parts.push('  wireLyricChip();');
parts.push('}');
parts.push('');
parts.push('function onSmartInput(){');
parts.push('  const input=document.getElementById("smartSearchInput");');
parts.push('  const val=input.value.trim();');
parts.push('  clearTimeout(geniusTimer);');
parts.push('  if(!val){clearSongSelection();closeSheet();return;}');
parts.push('  if(geniusResult){geniusResult=null;clearSongPill();clearYoutubePreview();hideLyricChip();}');
parts.push('  if(val.length<2)return;');
parts.push('  showSearchingState();');
parts.push('  openSheet();');
parts.push('  const cacheKey=val.toLowerCase();');
parts.push('  if(searchCache[cacheKey]){renderSheetResults(searchCache[cacheKey]);return;}');
parts.push('  geniusTimer=setTimeout(function(){runSmartSearch(val);},380);');
parts.push('}');
parts.push('');
parts.push('async function runSmartSearch(query){');
parts.push('  if(query===lastQuery)return;');
parts.push('  lastQuery=query;');
parts.push('  try{');
parts.push('    const res=await fetch("/api/genius?lyric="+encodeURIComponent(query));');
parts.push('    const data=await res.json();');
parts.push('    const results=(res.ok&&data.results&&data.results.length)?data.results:[];');
parts.push('    searchCache[query.toLowerCase()]=results;');
parts.push('    if(results.length)renderSheetResults(results);');
parts.push('    else showNoResults();');
parts.push('  }catch(err){showNoResults();}');
parts.push('}');
parts.push('');
parts.push('function injectSearchSheet(){');
parts.push('  if(document.getElementById("searchSheet"))return;');
parts.push('  const shareInputs=document.getElementById("shareInputs");');
parts.push('  if(!shareInputs)return;');
parts.push('  const q=\'"\';');
parts.push('  shareInputs.innerHTML=');
parts.push('    "<div id="+q+"smartSearchWrap"+q+" class="+q+"smart-search-wrap"+q+">"');
parts.push('    +"<div class="+q+"smart-search-field"+q+">"');
parts.push('    +"<span class="+q+"smart-search-icon"+q+"><svg width="+q+"14"+q+" height="+q+"14"+q+" viewBox="+q+"0 0 24 24"+q+" fill="+q+"none"+q+" stroke="+q+"currentColor"+q+" stroke-width="+q+"2.5"+q+" stroke-linecap="+q+"round"+q+" stroke-linejoin="+q+"round"+q+"><circle cx="+q+"11"+q+" cy="+q+"11"+q+" r="+q+"8"+q+"/><path d="+q+"m21 21-4.35-4.35"+q+"/></svg></span>"');
parts.push('    +"<input id="+q+"smartSearchInput"+q+" type="+q+"text"+q+" inputmode="+q+"text"+q+" autocomplete="+q+"off"+q+" autocorrect="+q+"off"+q+" spellcheck="+q+"false"+q+" class="+q+"smart-search-input"+q+" placeholder="+q+"Search by lyric, song or artist\u2026"+q+"/>"');
parts.push('    +"<span id="+q+"searchSpinner"+q+" class="+q+"search-spinner hidden"+q+"></span>"');
parts.push('    +"<button id="+q+"clearSearchBtn"+q+" class="+q+"clear-search-btn hidden"+q+" aria-label="+q+"Clear"+q+">\u00d7</button>"');
parts.push('    +"</div>"');
parts.push('    +"<div id="+q+"songPill"+q+" class="+q+"song-pill hidden"+q+">"');
parts.push('    +"<span class="+q+"song-pill-art-wrap"+q+"><img id="+q+"songPillArt"+q+" class="+q+"song-pill-art"+q+" src="+q+q+" alt="+q+q+"/><span class="+q+"song-pill-art-fallback"+q+">\u266a</span></span>"');
parts.push('    +"<span class="+q+"song-pill-info"+q+"><span id="+q+"songPillName"+q+" class="+q+"song-pill-name"+q+"></span><span id="+q+"songPillArtist"+q+" class="+q+"song-pill-artist"+q+"></span></span>"');
parts.push('    +"<button id="+q+"changeSongBtn"+q+" class="+q+"song-pill-change"+q+">Change</button>"');
parts.push('    +"</div></div>"');
parts.push('    +"<div id="+q+"searchSheet"+q+" class="+q+"search-sheet hidden"+q+">"');
parts.push('    +"<div class="+q+"search-sheet-inner"+q+">"');
parts.push('    +"<div id="+q+"searchSheetStatus"+q+" class="+q+"search-sheet-status"+q+"></div>"');
parts.push('    +"<div id="+q+"searchSheetResults"+q+" class="+q+"search-sheet-results"+q+"></div>"');
parts.push('    +"</div></div>"');
parts.push('    +"<input id="+q+"songInput"+q+" type="+q+"hidden"+q+" value="+q+q+"/>"');
parts.push('    +"<input id="+q+"artistInput"+q+" type="+q+"hidden"+q+" value="+q+q+"/>";');
parts.push('  document.getElementById("clearSearchBtn").addEventListener("click",function(){');
parts.push('    clearSongSelection();');
parts.push('    var input=document.getElementById("smartSearchInput");');
parts.push('    if(input){input.value="";input.focus();}');
parts.push('    closeSheet();');
parts.push('  });');
parts.push('  document.getElementById("changeSongBtn").addEventListener("click",function(){');
parts.push('    geniusResult=null;clearSongPill();clearYoutubePreview();hideLyricChip();hideVibeSection();');
parts.push('    var input=document.getElementById("smartSearchInput");');
parts.push('    if(input){input.value="";input.focus();}');
parts.push('    hideSongPill();');
parts.push('  });');
parts.push('}');
parts.push('');
parts.push('/* ── Lyric chip ── */');
parts.push('function wireLyricChip(){');
parts.push('  const editBtn=document.getElementById("lyricChipEdit");');
parts.push('  if(!editBtn)return;');
parts.push('  editBtn.addEventListener("click",function(){');
parts.push('    const editWrap=document.getElementById("lyricEditWrap");');
parts.push('    if(!editWrap)return;');
parts.push('    const isHidden=editWrap.classList.contains("hidden");');
parts.push('    editWrap.classList.toggle("hidden",!isHidden);');
parts.push('    if(isHidden){');
parts.push('      const ta=document.getElementById("textInput");');
parts.push('      if(ta){ta.focus();ta.setSelectionRange(ta.value.length,ta.value.length);}');
parts.push('    }');
parts.push('  });');
parts.push('  const ta=document.getElementById("textInput");');
parts.push('  if(ta){');
parts.push('    ta.addEventListener("input",function(){');
parts.push('      const chip=document.getElementById("lyricChipText");');
parts.push('      if(chip)chip.textContent=ta.value||"Add your line\u2026";');
parts.push('      const cc=document.getElementById("charCount");');
parts.push('      if(cc)cc.textContent=ta.value.length;');
parts.push('    });');
parts.push('  }');
parts.push('}');
parts.push('');
parts.push('function showLyricChip(lyric){');
parts.push('  const wrap=document.getElementById("lyricChipWrap");');
parts.push('  const chip=document.getElementById("lyricChipText");');
parts.push('  const ta=document.getElementById("textInput");');
parts.push('  const cc=document.getElementById("charCount");');
parts.push('  if(!wrap||!chip)return;');
parts.push('  const text=lyric.substring(0,140);');
parts.push('  chip.textContent=text;');
parts.push('  if(ta){ta.value=text;}');
parts.push('  if(cc){cc.textContent=text.length;}');
parts.push('  wrap.classList.remove("hidden");');
parts.push('  showVibeSection();');
parts.push('}');
parts.push('');
parts.push('function hideLyricChip(){');
parts.push('  const wrap=document.getElementById("lyricChipWrap");');
parts.push('  if(wrap)wrap.classList.add("hidden");');
parts.push('  const ta=document.getElementById("textInput");');
parts.push('  if(ta)ta.value="";');
parts.push('  hideVibeSection();');
parts.push('}');
parts.push('');
parts.push('function showVibeSection(){');
parts.push('  const vl=document.getElementById("vibeLabel");');
parts.push('  const eg=document.getElementById("emotionGrid");');
parts.push('  const footer=document.querySelector(".modal-footer");');
parts.push('  if(vl)vl.style.display="";');
parts.push('  if(eg)eg.style.display="";');
parts.push('  if(footer)footer.style.display="";');
parts.push('}');
parts.push('');
parts.push('function hideVibeSection(){');
parts.push('  const vl=document.getElementById("vibeLabel");');
parts.push('  const eg=document.getElementById("emotionGrid");');
parts.push('  const footer=document.querySelector(".modal-footer");');
parts.push('  if(vl)vl.style.display="none";');
parts.push('  if(eg)eg.style.display="none";');
parts.push('  if(footer)footer.style.display="none";');
parts.push('}');
parts.push('');
parts.push('/* ── Sheet open/close ── */');
parts.push('function openSheet(){');
parts.push('  const sheet=document.getElementById("searchSheet");');
parts.push('  if(!sheet||isSheetOpen)return;');
parts.push('  sheet.classList.remove("hidden");');
parts.push('  requestAnimationFrame(function(){sheet.classList.add("open");});');
parts.push('  isSheetOpen=true;');
parts.push('}');
parts.push('');
parts.push('function closeSheet(){');
parts.push('  const sheet=document.getElementById("searchSheet");');
parts.push('  if(!sheet)return;');
parts.push('  sheet.classList.remove("open");');
parts.push('  setTimeout(function(){sheet.classList.add("hidden");},220);');
parts.push('  isSheetOpen=false;');
parts.push('}');
parts.push('');
parts.push('function showSearchingState(){');
parts.push('  const status=document.getElementById("searchSheetStatus");');
parts.push('  const results=document.getElementById("searchSheetResults");');
parts.push('  const spinner=document.getElementById("searchSpinner");');
parts.push('  const q=\'"\';');
parts.push('  if(status)status.innerHTML="<span class="+q+"search-identifying"+q+"><span class="+q+"search-pulse"+q+"></span>Identifying\u2026</span>";');
parts.push('  if(results)results.innerHTML="";');
parts.push('  if(spinner)spinner.classList.remove("hidden");');
parts.push('}');
parts.push('');
parts.push('function showNoResults(){');
parts.push('  const status=document.getElementById("searchSheetStatus");');
parts.push('  const results=document.getElementById("searchSheetResults");');
parts.push('  const spinner=document.getElementById("searchSpinner");');
parts.push('  const q=\'"\';');
parts.push('  if(status)status.innerHTML="<span class="+q+"search-no-result"+q+">Try a different line or song name</span>";');
parts.push('  if(results)results.innerHTML="";');
parts.push('  if(spinner)spinner.classList.add("hidden");');
parts.push('}');
parts.push('');
parts.push('function renderSheetResults(results){');
parts.push('  const status=document.getElementById("searchSheetStatus");');
parts.push('  const list=document.getElementById("searchSheetResults");');
parts.push('  const spinner=document.getElementById("searchSpinner");');
parts.push('  const q=\'"\';');
parts.push('  if(spinner)spinner.classList.add("hidden");');
parts.push('  if(status)status.innerHTML="<span class="+q+"search-found-label"+q+">Select the right song</span>";');
parts.push('  if(!list)return;');
parts.push('  list.innerHTML="";');
parts.push('  results.forEach(function(r,idx){');
parts.push('    const song=decodeHTML(r.song||""),artist=decodeHTML(r.artist||"");');
parts.push('    const card=document.createElement("div");');
parts.push('    card.className="search-result-card";');
parts.push('    card.style.animationDelay=idx*55+"ms";');
parts.push('    const img=r.artwork');
parts.push('      ? "<img src="+q+r.artwork+q+" class="+q+"search-result-art"+q+" alt="+q+q+"/>"');
parts.push('      : "<div class="+q+"search-result-art search-result-art-fallback"+q+">\u266a</div>";');
parts.push('    card.innerHTML=img');
parts.push('      +"<div class="+q+"search-result-info"+q+"><div class="+q+"search-result-song"+q+">"+song+"</div><div class="+q+"search-result-artist"+q+">"+artist+"</div></div>"');
parts.push('      +"<span class="+q+"search-result-use"+q+">Use</span>";');
parts.push('    card.addEventListener("pointerdown",function(e){');
parts.push('      e.preventDefault();');
parts.push('      selectResult(Object.assign({},r,{song:song,artist:artist}),card);');
parts.push('    });');
parts.push('    list.appendChild(card);');
parts.push('  });');
parts.push('}');
parts.push('');
parts.push('function selectResult(result,card){');
parts.push('  document.querySelectorAll(".search-result-card").forEach(function(c){c.classList.remove("selected");});');
parts.push('  if(card){');
parts.push('    card.classList.add("selected");');
parts.push('    const tag=card.querySelector(".search-result-use");');
parts.push('    if(tag)tag.textContent="\u2713";');
parts.push('  }');
parts.push('  geniusResult=result;');
parts.push('  const songEl=document.getElementById("songInput");');
parts.push('  const artistEl=document.getElementById("artistInput");');
parts.push('  if(songEl)songEl.value=result.song;');
parts.push('  if(artistEl)artistEl.value=result.artist;');
parts.push('  showSongPill(result);');
parts.push('  // Auto-fill lyric from search query');
parts.push('  const searchVal=document.getElementById("smartSearchInput").value.trim();');
parts.push('  showLyricChip(searchVal);');
parts.push('  if(result.id)fetchGeniusDetail(result.id);');
parts.push('  clearYoutubePreview();');
parts.push('  fetchYoutubeData(result.song,result.artist);');
parts.push('  setTimeout(function(){closeSheet();},280);');
parts.push('}');
parts.push('');
parts.push('function showSongPill(result){');
parts.push('  const pill=document.getElementById("songPill");');
parts.push('  const nameEl=document.getElementById("songPillName");');
parts.push('  const artEl=document.getElementById("songPillArtist");');
parts.push('  const imgEl=document.getElementById("songPillArt");');
parts.push('  const input=document.getElementById("smartSearchInput");');
parts.push('  if(nameEl)nameEl.textContent=result.song;');
parts.push('  if(artEl)artEl.textContent=result.artist;');
parts.push('  if(imgEl&&result.artwork){imgEl.src=result.artwork;imgEl.style.display="block";}');
parts.push('  if(pill)pill.classList.remove("hidden");');
parts.push('  const field=input&&input.closest(".smart-search-field");');
parts.push('  if(field)field.style.display="none";');
parts.push('  const wrap=document.getElementById("smartSearchWrap");');
parts.push('  if(wrap)wrap.classList.add("has-selection");');
parts.push('}');
parts.push('');
parts.push('function hideSongPill(){');
parts.push('  const pill=document.getElementById("songPill");');
parts.push('  const input=document.getElementById("smartSearchInput");');
parts.push('  const wrap=document.getElementById("smartSearchWrap");');
parts.push('  if(pill)pill.classList.add("hidden");');
parts.push('  const field=input&&input.closest(".smart-search-field");');
parts.push('  if(field)field.style.display="";');
parts.push('  if(wrap)wrap.classList.remove("has-selection");');
parts.push('}');
parts.push('');
parts.push('function clearSongPill(){');
parts.push('  hideSongPill();');
parts.push('  const s=document.getElementById("songInput"),a=document.getElementById("artistInput");');
parts.push('  if(s)s.value="";if(a)a.value="";');
parts.push('}');
parts.push('');
parts.push('function clearSongSelection(){');
parts.push('  geniusResult=null;lastQuery="";');
parts.push('  clearSongPill();clearYoutubePreview();hideLyricChip();');
parts.push('  const sp=document.getElementById("searchSpinner");');
parts.push('  if(sp)sp.classList.add("hidden");');
parts.push('}');
parts.push('');
parts.push('function initYoutubeAutofetch(){}');
parts.push('');
parts.push('async function fetchYoutubeData(song,artist){');
parts.push('  const cleanSong=song.replace(/\\s*[\\(\\[].*?[\\)\\]]/g,"").trim();');
parts.push('  const cleanArtist=artist.replace(/\\s*feat\\..*$/i,"").replace(/\\s*ft\\..*$/i,"").trim();');
parts.push('  showYtLoading();youtubeData=null;');
parts.push('  try{');
parts.push('    const res=await fetch("/api/youtube?song="+encodeURIComponent(cleanSong)+"&artist="+encodeURIComponent(cleanArtist));');
parts.push('    const data=await res.json();');
parts.push('    if(!res.ok||data.error||(!data.videoId&&!data.thumbnail)){clearYoutubePreview();return;}');
parts.push('    youtubeData=data;renderYtCard(data);');
parts.push('  }catch(_){clearYoutubePreview();}');
parts.push('}');
parts.push('');
parts.push('function showYtLoading(){');
parts.push('  clearYoutubePreview();');
parts.push('  const q=\'"\';');
parts.push('  const card=document.createElement("div");');
parts.push('  card.id="youtubePreview";card.className="yt-card";');
parts.push('  card.innerHTML="<div class="+q+"yt-loading"+q+"><span class="+q+"m-spinner"+q+"></span>Looking up on YouTube, Deezer, Apple Music\u2026</div>";');
parts.push('  insertAfterSearch(card);');
parts.push('}');
parts.push('');
parts.push('function renderYtCard(data){');
parts.push('  clearYoutubePreview();');
parts.push('  const source=data.source||"youtube";');
parts.push('  const links=[];');
parts.push('  const q=\'"\';');
parts.push('  if(data.youtubeUrl)links.push("<a href="+q+data.youtubeUrl+q+" target="+q+"_blank"+q+" rel="+q+"noopener"+q+" class="+q+"yt-listen-link yt-link-yt"+q+">YouTube</a>");');
parts.push('  if(data.deezerUrl)links.push("<a href="+q+data.deezerUrl+q+" target="+q+"_blank"+q+" rel="+q+"noopener"+q+" class="+q+"yt-listen-link yt-link-dz"+q+">Deezer</a>");');
parts.push('  if(data.itunesUrl)links.push("<a href="+q+data.itunesUrl+q+" target="+q+"_blank"+q+" rel="+q+"noopener"+q+" class="+q+"yt-listen-link yt-link-it"+q+">Apple Music</a>");');
parts.push('  const cls=source==="youtube"?"yt-found-yt":source==="deezer"?"yt-found-dz":"yt-found-it";');
parts.push('  const thumb=data.thumbnail||data.thumbnailSm;');
parts.push('  const card=document.createElement("div");');
parts.push('  card.id="youtubePreview";card.className="yt-card";');
parts.push('  card.innerHTML="<div class="+q+"yt-card-inner"+q+">"');
parts.push('    +(thumb?"<div class="+q+"yt-thumb-wrap"+q+"><img src="+q+thumb+q+" class="+q+"yt-thumb"+q+" alt="+q+decodeHTML(data.title||"")+q+"/></div>":"")');
parts.push('    +"<div class="+q+"yt-info"+q+"><div class="+q+"yt-title"+q+">"+decodeHTML(data.title||"")+"</div>"');
parts.push('    +"<div class="+q+"yt-channel"+q+">"+decodeHTML(data.channel||data.collectionName||"")+"</div>"');
parts.push('    +(links.length?"<div class="+q+"yt-links-row"+q+">"+links.join("")+"</div>":"")');
parts.push('    +"</div><span class="+q+"yt-found-tag "+cls+q+">Found</span></div>";');
parts.push('  insertAfterSearch(card);');
parts.push('  const ytLink=document.getElementById("youtubeLink");');
parts.push('  if(ytLink&&!ytLink.value&&data.videoId&&data.youtubeUrl)ytLink.value=data.youtubeUrl;');
parts.push('}');
parts.push('');
parts.push('function insertAfterSearch(el){');
parts.push('  const wrap=document.getElementById("smartSearchWrap");');
parts.push('  if(wrap)wrap.parentNode.insertBefore(el,wrap.nextSibling);');
parts.push('}');
parts.push('');
parts.push('function clearYoutubePreview(){');
parts.push('  youtubeData=null;');
parts.push('  const el=document.getElementById("youtubePreview");');
parts.push('  if(el)el.remove();');
parts.push('}');
parts.push('');
parts.push('async function fetchGeniusDetail(id){');
parts.push('  try{');
parts.push('    const res=await fetch("/api/genius?id="+id);');
parts.push('    const data=await res.json();');
parts.push('    if(!res.ok||data.error)return;');
parts.push('    geniusResult=Object.assign({},geniusResult,{');
parts.push('      album:data.album||null,');
parts.push('      releaseDate:data.releaseDate||null,');
parts.push('      featuredArtists:data.featuredArtists||[],');
parts.push('      writers:data.writers||[],');
parts.push('      producers:data.producers||[]');
parts.push('    });');
parts.push('  }catch(_){}');
parts.push('}');
parts.push('');
parts.push('function closeAutocomplete(){closeSheet();}');

fs.writeFileSync(out, parts.join('\n'), 'utf8');
console.log('done, lines:', parts.length);

// Also append lyric chip CSS
const cssOut = require('path').join(__dirname, 'assets/css/composer.css');
const chipCss = [
'',
'/* LYRIC CHIP */',
'.lyric-chip-wrap{margin-top:14px;}',
'.lyric-chip-wrap.hidden{display:none;}',
'.lyric-chip{display:flex;align-items:center;gap:10px;padding:12px 14px;border-radius:14px;background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.10);transition:border-color 0.2s;}',
'.lyric-chip:focus-within{border-color:rgba(232,197,71,0.35);}',
'.lyric-chip-text{flex:1;font-size:0.9rem;color:#fff;font-style:italic;opacity:0.85;line-height:1.4;min-width:0;word-break:break-word;}',
'.lyric-chip-edit{flex-shrink:0;background:none;border:1px solid rgba(255,255,255,0.12);border-radius:8px;color:rgba(255,255,255,0.4);width:30px;height:30px;display:flex;align-items:center;justify-content:center;cursor:pointer;font-size:0.75rem;transition:all 0.15s;}',
'.lyric-chip-edit:hover{border-color:rgba(232,197,71,0.4);color:#E8C547;background:rgba(232,197,71,0.06);}',
'.lyric-edit-wrap{margin-top:10px;}',
'.lyric-edit-wrap.hidden{display:none;}',
'.lyric-edit-wrap textarea{width:100%;background:rgba(255,255,255,0.04);border:1px solid rgba(232,197,71,0.3);border-radius:12px;padding:12px 14px;color:#fff;font-size:0.9rem;resize:none;outline:none;min-height:72px;caret-color:#E8C547;box-sizing:border-box;}',
'.lyric-edit-wrap textarea:focus{border-color:rgba(232,197,71,0.55);box-shadow:0 0 0 3px rgba(232,197,71,0.08);}',
].join('\n');
require('fs').appendFileSync(cssOut, chipCss, 'utf8');
console.log('css appended');
